# Generated by Django 5.0.6 on 2024-06-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRecommendationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('rcmlist', models.TextField()),
            ],
        ),
    ]
